name: bootstrap
version: 4.2.1

author: Cédric Belin <cedric@belin.io>
description: The most popular front-end framework for developing responsive, mobile first projects on the Web.
documentation: https://dev.belin.io/boostrap.dart/api
homepage: https://dev.belin.io/boostrap.dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  grinder: ^0.8.3
  package_resolver: ^1.0.6
  sass: ^1.15.3
